[tools]
crystal = "latest"

[tasks.deps]
run = "shards install"

[tasks.test]
run = ["shards install", "mkdir -p .crystal/cache", "CRYSTAL_CACHE_DIR=.crystal/cache crystal spec"]

[tasks.build]
run = ["shards install", "mkdir -p .crystal/cache", "CRYSTAL_CACHE_DIR=.crystal/cache shards build --release"]

[tasks.package]
run = ["shards install", "mkdir -p .crystal/cache", "CRYSTAL_CACHE_DIR=.crystal/cache shards build --release", "bash scripts/package.sh"]
