# syntax=docker/dockerfile:1.7

FROM crystallang/crystal:1.12.2-alpine AS builder

RUN apk add --no-cache \
  bash \
  build-base \
  sqlite-dev \
  sqlite-static \
  shards

WORKDIR /src
COPY shard.yml shard.lock ./
RUN shards install

COPY . .
RUN CRYSTAL_CACHE_DIR=/tmp/.crystal-cache \
  mkdir -p /out && \
  crystal build src/actra.cr --release --static -o /out/actra

FROM scratch
COPY --from=builder /out/actra /usr/local/bin/actra
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENTRYPOINT ["/usr/local/bin/actra"]
