name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    tags: ["*"]
    branches: ["release"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - run: bash .meta/packaging/scripts/test-homebrew-packaging.sh
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - run: shards install
      - run: crystal spec
      - run: shards build --release
